config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'

  get 'users/new'
  
  root             'static_pages#home'
  get 'help'    => 'static_pages#help'
  get 'about'   => 'static_pages#about'
  get 'contact' => 'static_pages#contact'
  get 'signup'  => 'users#new'

  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'
  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :users
  resources :account_activations, only: [:edit]
  resources :microposts,          only: [:create, :destroy]
  resources :relationships,       only: [:create, :destroy]

end

app/models/micropost.rb
class Micropost < ActiveRecord::Base
	belongs_to :user
	default_scope -> { order(created_at: :desc) }
	mount_uploader :picture, PictureUploader
	validates :user_id, presence: true
	validates :content, presence: true, length: { maximum: 140 }
	validate  :picture_size

	private

    # Valide la taille de l'image uploader
    def picture_size
      if picture.size > 5.megabytes
        errors.add(:picture, "Doit être inférieur à 5MB")
      end
    end
end

app/controllers/microposts_controller.rb
class MicropostsController < ApplicationController
  before_action :logged_in_user, only: [:create, :destroy]
  before_action :correct_user,   only: :destroy
  # Permet de créer un post
  def create
    @micropost = current_user.microposts.build(micropost_params)
    if @micropost.save
      flash[:success] = "Micropost créer!"
      redirect_to root_url
    else
      @feed_items = []
      render 'static_pages/home'
    end
  end
  # Permet de supprimer un post
  def destroy
    @micropost.destroy
    flash[:success] = "Micropost supprimer"
    redirect_to request.referrer || root_url
  end

  private

  def micropost_params
    params.require(:micropost).permit(:content, :picture)
  end
  def correct_user
    @micropost = current_user.microposts.find_by(id: params[:id])
    redirect_to root_url if @micropost.nil?
  end
end

app/helpers/microposts_helper.rb
module MicropostsHelper
end

app/views/microposts/_form.html.erb
<%= form_for(@micropost) do |f| %>
  <% if @micropost.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@micropost.errors.count, "erreur") %> prohibited this micropost from being saved:</h2>

      <ul>
      <% @micropost.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :content %><br>
    <%= f.text_area :content %>
  </div>
  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.number_field :user_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/microposts/_micropost.html.erb
<li id="micropost-<%= micropost.id %>">
	<%= link_to gravatar_for(micropost.user), micropost.user %>
	<span class="user"><%= link_to micropost.user.name, micropost.user %></span>
	<span class="content">
		<%= micropost.content %>
		<%= image_tag micropost.picture.url if micropost.picture? %>
	</span>
	<span class="timestamp">
		Posté il y a <%= time_ago_in_words(micropost.created_at) %>.
		<% if current_user?(micropost.user) %>
		<%= link_to "Supprimer", micropost, method: :delete,
		data: { confirm: "Vous êtes sur?" } %>
		<% end %>
	</span>
</li>

app/views/microposts/edit.html.erb
<h1>Editing Micropost</h1>

<%= render 'form' %>

<%= link_to 'Show', @micropost %> |
<%= link_to 'Back', microposts_path %>

app/views/microposts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Liste Microposts</h1>

<table>
  <thead>
    <tr>
      <th>Contenu</th>
      <th>Utilisateurs</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @microposts.each do |micropost| %>
      <tr>
        <td><%= micropost.content %></td>
        <td><%= micropost.user_id %></td>
        <td><%= link_to 'Voir', micropost %></td>
        <td><%= link_to 'Modifier', edit_micropost_path(micropost) %></td>
        <td><%= link_to 'Supprimer', micropost, method: :delete, data: { confirm: 'Vous êtes sur?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Nouveau Micropost', new_micropost_path %>

app/views/microposts/new.html.erb
<h1>Nouveau micropost</h1>

<%= render 'form' %>

<%= link_to 'Retour', microposts_path %>

app/views/microposts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Content:</strong>
  <%= @micropost.content %>
</p>

<p>
  <strong>User:</strong>
  <%= @micropost.user_id %>
</p>

<%= link_to 'Edit', edit_micropost_path(@micropost) %> |
<%= link_to 'Back', microposts_path %>